import { useRef, useState } from 'react';
import { ImagePlus, Mic, Pause, Play, Send, Square, Type } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { createRecord } from '../lib/api';
type CaptureMode = 'picker' | 'post' | 'voice';

export function CaptureSheet({ open, onClose, onCollected }: { open: boolean; onClose: () => void; onCollected: (message: string) => void }) {
  const [mode, setMode] = useState<CaptureMode>('picker'); const [text, setText] = useState(''); const [imageAdded, setImageAdded] = useState(false); const [voiceState, setVoiceState] = useState<'idle' | 'recording' | 'paused'>('idle'); const [saving, setSaving] = useState(false); const lock = useRef(false); const client = useQueryClient();
  function reset() { setMode('picker'); setText(''); setImageAdded(false); setVoiceState('idle'); setSaving(false); } function dismiss() { reset(); onClose(); }
  async function saveText() { if (!text.trim() || lock.current) return; lock.current = true; setSaving(true); try { await createRecord(text.trim()); await client.invalidateQueries({ queryKey: ['records'] }); dismiss(); onCollected('Loomi 已收下这根线。'); } finally { lock.current = false; setSaving(false); } }
  function finishVoice() { if (voiceState === 'idle') return; dismiss(); onCollected('Loomi 已收下这段声音。'); }
  if (!open) return null;
  return <div className="capture-layer" role="presentation"><button className="capture-backdrop" aria-label="关闭捕获抽屉" onClick={dismiss} /><section className="capture-sheet" aria-label="捕获念头"><div className="sheet-grabber" />
    {mode === 'picker' && <><h2>收下一根新线</h2><p className="sheet-description">选择最适合此刻的方式，Loomi 会替你把它留好。</p><div className="capture-options"><button onClick={() => setMode('post')}><span><Type size={22} /></span><strong>图文</strong><small>写下想法，附上一张图</small></button><button onClick={() => setMode('voice')}><span><Mic size={22} /></span><strong>语音</strong><small>说出来，稍后再回看</small></button></div></>}
    {mode === 'post' && <><div className="sheet-top"><button className="sheet-back" onClick={() => setMode('picker')}>‹</button><span>图文记录</span><button className="sheet-close" onClick={dismiss}>关闭</button></div><textarea className="capture-textarea" autoFocus value={text} onChange={event => setText(event.target.value)} placeholder="这一刻，有什么值得留下？" />{imageAdded ? <div className="image-placeholder"><ImagePlus size={22} /><span>已添加图片</span><button onClick={() => setImageAdded(false)}>移除</button></div> : <button className="add-image" onClick={() => setImageAdded(true)}><ImagePlus size={19} />添加图片</button>}<div className="sheet-actions"><span>{text.length ? `${text.length} 字` : '随手记下就好'}</span><button className="sheet-submit" disabled={!text.trim() || saving} onClick={saveText}>{saving ? '保存中…' : <><span>收下</span><Send size={16} /></>}</button></div></>}
    {mode === 'voice' && <><div className="sheet-top"><button className="sheet-back" onClick={() => setMode('picker')}>‹</button><span>语音记录</span><button className="sheet-close" onClick={dismiss}>关闭</button></div><div className={`voice-stage ${voiceState}`}><div className="voice-orb"><Mic size={30} /></div><strong>{voiceState === 'idle' ? '准备开始' : voiceState === 'paused' ? '已暂停' : '正在收集声音'}</strong><span>{voiceState === 'idle' ? '用语音留下一段想法' : '00:12'}</span><div className="voice-wave" aria-hidden="true">{Array.from({ length: 15 }, (_, index) => <i key={index} style={{ height: `${16 + (index % 5) * 9}px` }} />)}</div></div><div className="voice-actions">{voiceState === 'recording' && <button onClick={() => setVoiceState('paused')}><Pause size={18} />暂停</button>}{voiceState === 'paused' && <button onClick={() => setVoiceState('recording')}><Play size={18} />继续</button>}{voiceState === 'idle' && <button className="voice-start" onClick={() => setVoiceState('recording')}><Mic size={20} />开始录音</button>}{voiceState !== 'idle' && <button className="voice-finish" onClick={finishVoice}><Square size={15} />结束并收下</button>}</div><p className="voice-note">录音功能为界面演示，暂不会请求麦克风权限。</p></>}
  </section></div>;
}
