import { useState, type PropsWithChildren, type ReactNode } from 'react';
import { ArrowLeft, AudioLines, Layers, Plus } from 'lucide-react';
import { useWorkspace } from '../lib/state';
import { go, back } from '../lib/router';
import { CaptureSheet } from './capture-sheet';
export { go, back } from '../lib/router';
export function Layout({ active, title, subtitle, headerMeta, children, detail = false, showBack = detail }: PropsWithChildren<{ active: 'records' | 'topics'; title: string; subtitle?: string; headerMeta?: ReactNode; detail?: boolean; showBack?: boolean }>) {
  const { organizing } = useWorkspace(); const [captureOpen, setCaptureOpen] = useState(false); const [notice, setNotice] = useState('');
  function collected(message: string) { setCaptureOpen(false); setNotice(message); window.setTimeout(() => setNotice(''), 2600); }
  return <div className="workspace"><main className={`main ${detail ? 'detail-main' : ''}`}>{showBack && <div className="detail-nav"><button className="icon-button" aria-label="返回" onClick={() => back(active)}><ArrowLeft size={21} /></button><span>{active === 'topics' ? '回声' : '记录'}</span></div>}<header className={`page-header ${detail ? 'detail-page-header' : 'primary-page-header'}`}><div><h1>{title}</h1>{subtitle && <p className="muted">{subtitle}</p>}{headerMeta}</div></header>{children}</main><nav className="bottom-nav loomi-nav" aria-label="主导航"><button className={`nav-item ${active === 'records' ? 'active' : ''}`} aria-current={active === 'records' ? 'page' : undefined} onClick={() => go('records')}><Layers size={21} strokeWidth={1.6} /><span>记录</span></button><button className="capture-trigger" aria-label="新增记录" onClick={() => setCaptureOpen(true)}><Plus size={25} strokeWidth={1.7} /></button><button className={`nav-item ${active === 'topics' ? 'active' : ''}`} aria-current={active === 'topics' ? 'page' : undefined} onClick={() => go('topics')}><AudioLines size={21} strokeWidth={1.6} /><span>回声</span>{organizing && <i className="running-dot" />}</button></nav><CaptureSheet open={captureOpen} onClose={() => setCaptureOpen(false)} onCollected={collected} />{notice && <div className="capture-notice" role="status">{notice}</div>}</div>;
}
export function ErrorNotice({ error, retry }: { error: Error | null; retry?: () => void }) { return error ? <div className="notice error" role="alert"><span>{error.message}</span>{retry && <button onClick={retry}>重试</button>}</div> : null; } export function Loading() { return <div className="empty" role="status">正在读取…</div>; } export function More({ hasMore, loading, onClick }: { hasMore: boolean; loading: boolean; onClick: () => void }) { return hasMore ? <button className="load-more" disabled={loading} onClick={onClick}>{loading ? '加载中…' : '加载更多'}</button> : null; }
